### ISSUE TITLE
Kicking my players, even after I uninstall???

### ISSUE THREAD

**Issue by bbans05** [RocketModPlugins/Observatory#4]
I get the program. No one AT ALL is able to join except for myself. I even uninstall the program but it is still happening. I really need an explanation as my players are spamming my website asking why they can't join and I can't fix this problem.

**Comment by sharkbound** [comment]
open the servers rocket folder, then open Rocket.Unturned.Config.xml, look for the 'RocketModObservatory' line in it, change ickLimitedAccounts="true" to KickLimitedAccounts="false".
and change KickTooYoungAccounts="true" to KickTooYoungAccounts="false"

**Comment by bbans05** [comment]
THANK YOU!!!!
